### ISSUE TITLE
System.deleteDirectory() Doesnt work in ur0:

### ISSUE THREAD

**Issue by SilicaAndPina** [Rinnegatamante/lpp-vita#10]
I found a bug where using System.deleteDirectory() doesnt delete directory located in ur0:

i tried it as System.deleteDirectory("ur0:/appmeta") and it threw no errors
the problem is ur0:/appmeta still exists!

**Comment by theorywrong** [comment]
have you tried eboot_unsafe.bin ?

**Comment by SilicaAndPina** [comment]
Yes, im using eboot_unsafe.bin.

in fact i can still write to ur0:appmeta via System.extractZIP its only when i use System.deleteDirectory it doesnt work.

**Comment by CelesteBlue-dev** [comment]
And how do you do to move a file ? I mean without using System.extractZIP.
thanks

**Comment by Rinnegatamante** [comment]
deleteDirectory is not recursive. Is ur0:/appmeta empty?

**Comment by theorywrong** [comment]
Yeah, error code: 0x8001005a DIRECTORY_NOT_EMPTY

**Comment by SilicaAndPina** [comment]
ooh that explains it!
Nevermind then

PS: You should add a recursive directory delete..

**Comment by Rinnegatamante** [comment]
Recursive delete directory is not available even in official SDK. It's just a matter of few minutes to write a proper recursive delete function. Example: https://github.com/Rinnegatamante/rinCheat/blob/master/SE_module/index.lua#L49-L60

**Comment by CelesteBlue-dev** [comment]
@Rinnegatamante Please may you add a function to move files from a src path to a dest path ?

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/lpp-vita/blob/master/source/luaSystem.cpp#L724
