### ISSUE TITLE
HTTP Requests

### ISSUE THREAD

**Issue by CodeAffe** [Rinnegatamante/lpp-vita#11]
The 3ds version supports http will the vita version?

**Comment by Rinnegatamante** [comment]
You can already exec an http request via sockets.

**Comment by Rinnegatamante** [comment]
Answered on phone and didn't have the time before, anyway here you are some examples:
- https://github.com/Rinnegatamante/lpp-vita/blob/master/samples/File%20Downloader/index.lua
- https://github.com/Rinnegatamante/rinCheat/blob/master/SE_module/index.lua#L62-L193
