### ISSUE TITLE
May you add a new release please ?

### ISSUE THREAD

**Issue by CelesteBlue-dev** [Rinnegatamante/lpp-vita#12]
The latest release is 49 commits behind...
Thank you very much

**Comment by Rinnegatamante** [comment]
http://rinnegatamante.it/lpp-nightly.php

**Comment by Rinnegatamante** [comment]
Regarding this, seems the VPS is still outdated (seems to be on something like 8-9 commits behind master. I'll fix this tomorrow.

**Comment by CelesteBlue-dev** [comment]
On that link it's written 3 april... We are on 6th May. 
On github latest release is 4th May.

**Comment by Rinnegatamante** [comment]
"Regarding this, seems the VPS is still outdated (seems to be on something like 8-9 commits behind master. I'll fix this tomorrow."

Nice reading skill, my friend.

**Comment by CelesteBlue-dev** [comment]
I tell that because I don't understand why you told "8-9 commits behind" while I see 49 commits behind...

**Comment by Rinnegatamante** [comment]
Commit of the Nightly (there's even a link on the page i linked to the commit it is on): https://github.com/Rinnegatamante/lpp-vita/tree/0347c991d05868b5e6e482231f81dcc9e925fac6

This commit is 15 commits behind master and some commits are just README changes = 8-9 commits behind master.

**Comment by CelesteBlue-dev** [comment]
ok thank you, so there are only two weird things : 
- No nigthly build since April 3rd 2017
- April 3rd 2017 nightly build is showing the December 6th 2016 commit... weird
Thank you anyway.

**Comment by Rinnegatamante** [comment]
- VPS got hardware updated and probably messed up my cronjob tasks.
- Probably some fault in git due to GitHub issues, a make clean from VPS console will solve the issue.

**Comment by CelesteBlue-dev** [comment]
😚

**Comment by Rinnegatamante** [comment]
Fixed: http://rinnegatamante.it/lpp-nightly.php

**Comment by CelesteBlue-dev** [comment]
Thank you.
