### ISSUE TITLE
Screen.getPixel()

### ISSUE THREAD

**Issue by ramersonw** [Rinnegatamante/lpp-vita#14]
How to use this function?

This sample is correct?

```
px = 0
while true do
	Graphics.initBlend()
	Screen.clear(Color.new(255,204,0))
	Graphics.debugPrint(200, 5, px, Color.new(255,255,255) )
       Graphics.termBlend()
	Screen.flip()
	px = Screen.getPixel(10,10)
end
```

I'm getting only negative values

if I put above Screen.flip(), I have the same result

**Comment by Rinnegatamante** [comment]
The returned value must be parsed with Color funcs (Color.getR, Color.getB, Color.getG, Color.getA).

**Comment by ramersonw** [comment]
Thanks, I get it now.
