### ISSUE TITLE
Graphics.drawPixel not working

### ISSUE THREAD

**Issue by ramersonw** [Rinnegatamante/lpp-vita#15]
in this sample below, drawPixel() does nothing:
```
while true do
  Graphics.initBlend()
  Screen.clear()  
  Graphics.drawLine(10, 25, 100, 250, Color.new(25, 200, 120))
  Graphics.fillRect(260, 275, 350, 500, Color.new(25, 200, 120))
  Graphics.drawPixel(5, 5, Color.new(25, 200, 120))
  Graphics.termBlend()
  Screen.flip()  
  if Controls.check(Controls.read(), SCE_CTRL_TRIANGLE) then
    System.exit()
  end
end
```

**Comment by Rinnegatamante** [comment]
The drawn pixel is really small, are you sure it doesn't work?

**Comment by ramersonw** [comment]
Here some screenshots of above code:
![2017-08-05-232832](https://user-images.githubusercontent.com/319450/29000070-a8e01eb4-7a36-11e7-9d5a-6d67c1bb94af.png)
and here, after I put Graphics.debugPrint(). The dot appears, but very large
![2017-08-05-233102](https://user-images.githubusercontent.com/319450/29000065-9ccf0144-7a36-11e7-8544-725dccbe9ce1.png)

Tests was made with R6

**Comment by Rinnegatamante** [comment]
Seems like a bug in vita2d. Will be addressed soon but in the meantime, you can use a Graphics.fillRect with width and height of 1 to reproduce the same behaviour of drawPixel.

**Comment by ramersonw** [comment]
Ok. I'll use Graphics.fillRect for now. Thanks.

**Comment by Rinnegatamante** [comment]
Solved with https://github.com/Rinnegatamante/lpp-vita/commit/7d4999cd4620fe0b88f13c7ef8dbde8aa4390d3d .
Will be available in next nightly.
