### ISSUE TITLE
Shrink the documentation logo

### ISSUE THREAD

**Issue by devnoname120** [Rinnegatamante/lpp-vita#17]
On my screen it makes the permanently-visible top header take 1/3 of the page height.

**Comment by Rinnegatamante** [comment]
That's kinda strange, on my PC, laptop and tablet, logo is correctly scaled. May you post a screenshot?

**Comment by devnoname120** [comment]
![](http://i.imgur.com/6lsZvop.png)

I emphasized the issue so that it be more visible.

**Comment by DTV96Calibre** [comment]
Seems like the banner just doesn't scale with window size. Should be as simple as making the banner area's height a percentage of the window's height.

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/lpp-vita/commit/2b91f26b64a3cda9e065f39e1a87b3781cece6ed
