### ISSUE TITLE
[Feature Request] Projection handling for 3d projects

### ISSUE THREAD

**Issue by ArkSource** [Rinnegatamante/lpp-vita#19]
Any plans to add functions to the Render Module for modifying the view matrix? (set 3d projection)

**Comment by Rinnegatamante** [comment]
A camera instance will come in the near future to handle this but for the moment, such instance can be handled in Lua.

**Comment by ArkSource** [comment]
Thanks for the quick reply Rinn, hope the Vacation has been relaxing.

Does lpp-vita accept 'require()' for our own Modules? I've been working on a Module but can't seem to get 'require()' working. (crashes when called. eg. require("core/engine") or require("app0:core/engine"))

dofile() works fine, but i was hoping to creating Modules for a more formal namespace and to avoid duplicates in larger projects.

**Comment by Rinnegatamante** [comment]
dofile works cause is patched on interpreter boot. Something similar should be done with require in order to get it working (look at luaPlayer.cpp + luaSystem.cpp )

**Comment by ArkSource** [comment]
Thanks for the information, i'll have a look into it today.

**Comment by Rinnegatamante** [comment]
Still not 100% tested but camera instance added with https://github.com/Rinnegatamante/lpp-vita/commit/a228c211fba38d119bd5c753c7cdef1b28be58a8 .

Will be available on next nightly.

**Comment by ArkSource** [comment]
(twiddles fingers one at a time) "Eeexcellent!"
very much appreciated.
