### ISSUE TITLE
trying add download 

### ISSUE THREAD

**Issue by modz2014** [Rinnegatamante/lpp-vita#20]
hi I'm trying to download a file using this 

-- Checking if connection is available
if Network.isWifiEnabled() then

	-- Download 
	Network.downloadFile("
	-- Loading image in memory and deleting it from storage
	img = Graphics.loadImage("ud0:/")
	

I have the other things sort but when I run it gives me error line 2 is there a different line to download a file

**Comment by Rinnegatamante** [comment]
Your code looks completely faulted. Check it again.

**Comment by modz2014** [comment]
-- Initializing Network
Network.init()

-- Checking if connection is available
if Network.isWifiEnabled() then

	-- Download an image
	Network.downloadFile("http://rinnegatamante.it/site/images/logo.png", "ux0:/data/data.png")

	-- Loading image in memory and deleting it from storage
	img = Graphics.loadImage("ux0:/data/data.png")
	System.deleteFile("ux0:/data/data.png")

end

-- Terminating network
Network.term()

-- Main loop
while true do
	
	-- Drawing the downloaded image
	Graphics.initBlend()
	Screen.clear()
	if img == nil then
		Graphics.debugPrint(5,220,"You must enable WiFi to use this sample.", Color.new(255,255,255))
		Graphics.debugPrint(5,240,"Press TRIANGLE to return to the sample selector", Color.new(255,255,255))
	else
		Graphics.drawImage(200,265,img)
		Graphics.debugPrint(5,220,"This image came from http://rinnegatamante.it/site/images/logo.png", Color.new(255,255,255))
		Graphics.debugPrint(5,240,"Press TRIANGLE to return to the sample selector", Color.new(255,255,255))
	end
	Graphics.termBlend()
	Screen.flip()
	
	-- Exit check
	if Controls.check(Controls.read(), SCE_CTRL_TRIANGLE) then
		if img ~= nil then
			Graphics.freeImage(img)
		end
		img = nil
		break
	end
	
end

**Comment by modz2014** [comment]
your one for example in there doesn't not work either
error line 2

**Comment by modz2014** [comment]
-- Checking if connection is available
if Network.isWifiEnabled then

	-- Download PUP
	Network.downloadFile("https://www.dropbox.com", "ux0:/app/image.img")
	
end
	
if System.doesFileExist("ux0:/uriCall_list.txt")==false then
	System.launchEboot("app0:devkit.bin")
	
end

**Comment by modz2014** [comment]
don't worry about where I downloading it from and too just don't get why there is errors

**Comment by modz2014** [comment]
Or what's the lines for moving a file scr to dest path

**Comment by Rinnegatamante** [comment]
I still don't get what's the problem, you're spamming random stuffs badly formatted that are hard to understand.

Btw, you're trying to download dropbox home (?) for what purpose?
Also, according to the fact you're trying to save the result on ux0:/app, i suppose you're using the unsafe build cause if not, safe build can write only on ux0:/data.

**Comment by modz2014** [comment]
Yes of cause unsafe don't worry about what I'm Dowloading I'm asking if it's right coz I get error at line too 

If It can't be done is there away for moving a file

**Comment by Rinnegatamante** [comment]
What error?

**Comment by modz2014** [comment]
Line two errror look at your same code for downloading image it's the same error

**Comment by Rinnegatamante** [comment]
The sample works fine and since you dont want to cooperate, i cant help you.

**Comment by modz2014** [comment]
I said I'm trying to create a script to download a file from dropbox then save it to a path ive tried heaps of was using http but I keep getting errors
