### ISSUE TITLE
trying to display progress bar

### ISSUE THREAD

**Issue by modz2014** [Rinnegatamante/lpp-vita#21]
hi man sorry about before in the other one I was trying to rush I will explain better this sorry please help me this is my code below

-- Starting progressbar message
					System.setMessage(".\nPlease wait...", true) 
					if System.doesFileExist("app0:/ud0_files.zip")==true then
					System.deleteDirectory("ud0:/")
					System.extractZIP("app0:ud0_files.zip", "ud0:/")

as you can see I'm trying to display a progress showing me when extracting the bar doesn't show but when I change if System.doesFileExist("app0:/ud0_files.zip")==true then to ==false then it display the progress bar but nothing gets extracted of course I think its a bug I'm not sure 
hopefully you can help me sorry one again about before

**Comment by Rinnegatamante** [comment]
Your code doesn't even render something on screen, that means a system message won't be rendered too.
Also, your code is faulty by default since the if clause is never closed resulting in a syntax error on script launch.

**Comment by modz2014** [comment]
would you like me to post the hole code ill upload it to hastebin

**Comment by modz2014** [comment]
https://hastebin.com/hubumapixu.lua

**Comment by Rinnegatamante** [comment]
extractZIP is a synchronous function, you can't bind a system message to a ZIP extraction.

**Comment by CelesteBlue-dev** [comment]
@Rinnegatamante Could you make it async please ? I mean maybe with a callback.
I think I saw extractZipCB in ONELUA.

**Comment by Rinnegatamante** [comment]
Asynchronous functions will be added in the future for several tasks for sure.

**Comment by modz2014** [comment]
so I cant do anything with this then until you update it

**Comment by Rinnegatamante** [comment]
Added with https://github.com/Rinnegatamante/lpp-vita/commit/94a61db265b45d9f95e258ba1cfd116271aac5bb
