### ISSUE TITLE
OSK numpad causes flickering bug

### ISSUE THREAD

**Issue by eleriaqueen** [Rinnegatamante/lpp-vita#24]
**How to reproduce ?**
Run script in which keyboard is shown, then press the numpad icon, you will see flicker just over the "symbols" keypad. I'm pretty sure it happens with lpp-vita keyboard sample code as well.

**Versions affected ?**
R6 as well as nightly dating of september 28 2017, I'm using safe eboot.

**Comment by Rinnegatamante** [comment]
Try to add Screen.waitVblankStart() before Screen.flip() call.

**Comment by eleriaqueen** [comment]
It works perfect ! Thanks.
I'm new to writing homebrew on the vita but made strides thanks to LPP, it's awesome.
