### ISSUE TITLE
font "bug"

### ISSUE THREAD

**Issue by svennd** [Rinnegatamante/lpp-vita#25]
Loading this font : https://fontlibrary.org/en/font/xolonium (regular) worked. However on subsequent attempts to run, it fails to load with the error "could not load font". A "restart" is enough to work.

This font : https://fontlibrary.org/en/font/archivo-narrow 

Crashed the entire app (system error) and a psp2dmp is created.

We discussed this on IRC, I hope this helps, if you need psp2dmp files I'm willing to send them.

Thx !

**Comment by svennd** [comment]
It might be possible that the "could not load font" was due to using https://github.com/TheOfficialFloW/VitaShell to edit app0:/ data. After a clean install (vpk) including the font the "could not load font" has not shown. 

So "basically" some fonts work some crash the application.

**Comment by svennd** [comment]
references : https://github.com/Rinnegatamante/lpp-vita/commit/c72b2407af7c4f426d2b0e05f857d377ddeb67df

I have found a few "could not load font", even on a freshly installed version. I'll try to check this evening if this bug fixes the archivo-narrow font. Thanks for the continued support !

**Comment by Rinnegatamante** [comment]
Have you compiled it on your own? Nightlies are not yet to master branch.

**Comment by svennd** [comment]
No, I will try later this week :)

The "could not load" issue was with the latest public release, but it was not a 1-time occurrence, that is why I reported it ;) hopefully this is now fixed ! Thanks !
