### ISSUE TITLE
document issue's

### ISSUE THREAD

**Issue by svennd** [Rinnegatamante/lpp-vita#26]
Just a few typo's :
- under Graphics > drawPartialImage two times the link, while one should be drawImageExtended
- under Network > requestStringAsync shows an example of Network.requestString()

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/lpp-vita/commit/11384cd4a20b0b3c1265d669fee320de2a2a01a0 .
