### ISSUE TITLE
require() crashes vita

### ISSUE THREAD

**Issue by svennd** [Rinnegatamante/lpp-vita#30]
Would it be possible to implement/patch the require() function in lua

**Comment by Rinnegatamante** [comment]
Did some researches on lua-jit. Try to use require("app0:/your_module") or require("app0:/your_module.lua") and let me know if it crashes.

**Comment by Rinnegatamante** [comment]
That should allow require usage. Scripts must be placed in app0: partition.
Let me know if it works so i can update VPS environment too.
[eboot_safe.zip](https://github.com/Rinnegatamante/lpp-vita/files/1479604/eboot_safe.zip)

**Comment by svennd** [comment]
Will try this weekend.

**Comment by svennd** [comment]
tried, failed. I tried both the 5x and 5.1-5.2 method, they both crash the lpp. I have the dumps but cannot post them here... 

Anyway its doable to work around with do() so its totally up to you if you wish to hunt for this bug.

**Comment by Rinnegatamante** [comment]
Can you pastebin the exact code you tried? Crashdumps too can be helpful.

**Comment by svennd** [comment]
Hey Rinny,

I tried these methods : http://lua-users.org/wiki/ModulesTutorial (adapted to vita hello world) the last one was : (there are both methods)

index.lua
```
mymodule = require("app0:/test.lua")
mymodule.foo()
```
test.lua
```
module("mymodule", package.seeall)

function foo()
	-- Create a new color
	local white = Color.new(255,255,255) 

	-- Main loop
	while true do
		
		-- Draw a string on the screen
		Graphics.initBlend()
		Screen.clear()
		Graphics.debugPrint(5, 5, "Hello World!", white)
		Graphics.debugPrint(5, 25, "Press TRIANGLE to return to the sample selector.", white)
		Graphics.termBlend()
		
		-- Update screen (For double buffering)
		Screen.flip()
		
		-- Check controls for exiting
		if Controls.check(Controls.read(), SCE_CTRL_TRIANGLE) then
			break
		end
		
	end
end
```

dump : 
https://ufile.io/ioblf

**Comment by Rinnegatamante** [comment]
You must use "test.lua" or "test" and place the script in app0:.

**Comment by svennd** [comment]
```
mymodule = require("app0:/test")
mymodule.foo()
```
this ?

**Comment by Rinnegatamante** [comment]
"test.lua" or "test", not "app0:test"...

**Comment by svennd** [comment]
both crash : 
https://ufile.io/wo766

**Comment by Rinnegatamante** [comment]
According to the crashdump, it's a issue related to vita-libdl: https://github.com/hyln9/vita-libdl/issues/1

**Comment by shadowbrony33** [comment]
Still an issue, I need this dearly for something I'm working on.

**Comment by svennd** [comment]
Yes, its still open. I hope this can get fixed some day, currently its not possible to load code w/o executing it directly, which is a huge help for keeping code clean. I tried to work around require() with loadfile() but that also does not work.

**Comment by Rinnegatamante** [comment]
This now works with replaced luajit+libdl.
