### ISSUE TITLE
Maybe i'm stupid but, drawLine()

### ISSUE THREAD

**Issue by Creckeryop** [Rinnegatamante/lpp-vita#33]
Can't draw " **/**  " line. if i draw " / " line i am getting " \ " line.
Maybe it's because you're switching y1 and y2 (if y2 < y1) in LuaGraphics.cpp (127 - 131) Lines
last nightly build

**Comment by Rinnegatamante** [comment]
That check was meant to be used for rectangles originally and got added to lines too. It's performed by lpp-3ds too.
Btw, at least on Vita, i think it's irrelevant and can be removed. Have to do some further tests.
In the meantime, can you post your code?

**Comment by Creckeryop** [comment]
```
while true do
	pad = Controls.read()
	Graphics.initBlend()
	Graphics.drawLine(0,960,544,0,Color.new(255,255,255)) -- "\"
	Graphics.drawLine(0,960,0,544,Color.new(255,255,255)) -- "/"
	Screen.clear()
	Graphics.termBlend()
	if Controls.check(pad, SCE_CTRL_START) and Controls.check(pad, SCE_CTRL_START) then
		System.exit()
	end
	Screen.flip()
	oldpad = pad
end
```
This code have to Give Cross 
![image](https://user-images.githubusercontent.com/25725992/33027756-d4c5f06e-ce35-11e7-9cc8-431512c3b0a0.png)
like this, but it gives
![image](https://user-images.githubusercontent.com/25725992/33027767-dcf00e96-ce35-11e7-8643-a33b342f6811.png)

**Comment by Rinnegatamante** [comment]
Should be addressed with https://github.com/Rinnegatamante/lpp-vita/commit/432e12c57135f1a79ea2efcf06f2d2cdc9ffb842 and available in next nightly.
