### ISSUE TITLE
Error 0x80AF5022 when installing File Manager sample

### ISSUE THREAD

**Issue by sqrg** [Rinnegatamante/lpp-vita#34]
Using lpp-vita r6, eboot_unsafe.bin and 'TTMT' as title ID; I get Error 0x80AF5022 when the vpk finishes installing.

Am I doing something wrong?

**Comment by sqrg** [comment]
Same error using latest nightly

**Comment by Rinnegatamante** [comment]
Upload your vpk somewhere.

**Comment by sqrg** [comment]
Sure

File Manager sample https://mega.nz/#!TF41mBqD!UGOohrmECbiiLJOJe4b0WIMIcAoyZrS5SYXdCqAxKX8
Image sample https://mega.nz/#!SJx02IZT!Ezl4pdLOMP_ByLUmTTq3npBPPxL-P2OoilO8sPCUarU

**Comment by Rinnegatamante** [comment]
eboot_unsafe.bin must be renamed eboot.bin (same for the safe one).

**Comment by sqrg** [comment]
Shit. I'm sorry, that was it.
