### ISSUE TITLE
Documentation error: Keyboard.start should be Keyboard.show

### ISSUE THREAD

**Issue by Kirezar** [Rinnegatamante/lpp-vita#40]
Documentation shows Keyboard.start as the function to start the keyboard, it's Keyboard.show instead

Version r6 and nightly

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/lpp-vita/commit/3c25b5fb3aaa7e0d65677f2485cfb70d5a1d3c33
