### ISSUE TITLE
JPEG System.takeScreenshot doesn't work

### ISSUE THREAD

**Issue by Creckeryop** [Rinnegatamante/lpp-vita#43]
0 bytes file appears

**Comment by Rinnegatamante** [comment]
A possible solution is to move from sceJpegEncoder to libjpeg usage for this. (lpp-3ds code can be taken into account for a solution: https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaSystem.cpp#L314-L356 + https://github.com/Rinnegatamante/lpp-3ds/blob/9b09073becb161299045534ed3ea4b3e976c1c34/source/include/graphics/Graphics.cpp#L1557-L1581

**Comment by Creckeryop** [comment]
sorry for false info, this function works properly.
### 0 bytes file appears in the next situations:
* takeScreenshot before first cycle of Graphics.initBlend() Graphics.termBlend();
* fast closing application (while takeScreenshot is working).
### Steps to prevent 0 byte screenshot in your app:
* lock Home button while takeScreenshot is active;
* be sure that takeScreenshot is called after at least one cycle of  Graphics.initBlend() Graphics.termBlend().
Sorry again.
