### ISSUE TITLE
error system.removeDir and system.doesDirExists

### ISSUE THREAD

**Issue by modz2014** [Rinnegatamante/lpp-vita#45]
having trouble with this does seem to work 

attempt to call field 'removeDir'(a nil vaule)

same for does doesDirExists

**Comment by Rinnegatamante** [comment]
removeDir and doesDirExists don't exist infact. http://rinnegatamante.github.io/lpp-vita/group___system.html

**Comment by modz2014** [comment]
ok i fixed it but you cant delete anything in pd0 or os0 using this i can only delete directory on ur0 or ux0

**Comment by modz2014** [comment]
i was going off this site http://wololo.net/talk/viewtopic.php?t=38493 thats why i read it wrong sorry

**Comment by Rinnegatamante** [comment]
Unsafe eboot most be used to delete stuffs outside of ux0:/data.

**Comment by modz2014** [comment]
so i have to delete the files then delete the directory
