### ISSUE TITLE
Video playback not looping

### ISSUE THREAD

**Issue by mellonfarmer** [Rinnegatamante/lpp-vita#53]
Hi,

Using the video sample, adding true to  Video.open on line 7 the video stops at the end of playback.

Not sure if I'm using the command incorrectly or it is a bug

Using most recent nightly build

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/lpp-vita/commit/f7c087397de687f7b3939a358a30961ea991892f
