### ISSUE TITLE
Unable to open file for writing

### ISSUE THREAD

**Issue by mellonfarmer** [Rinnegatamante/lpp-vita#54]
Hi,

Not sure if it's a bug or i'm not using the command properly, 

When using System.open with FWRITE, FRDWR, FCREATE gives error: cannot open requested file.
the issues doesn't appear when using FREAD

sample:

toWrite = "Hello world"
local fh = System.openFile("app0:/file.txt", FRDWR)
System.writeFile(fh, toWrite, #toWrite)
System.closeFile(fh)

error line 2

using Latest nightly build

**Comment by Rinnegatamante** [comment]
app0 is read only.

**Comment by mellonfarmer** [comment]
Sorry, should have noted that I have also tried it with the full installation directory as well ux0:/data/<appname>/file

**Comment by Rinnegatamante** [comment]
Assuming the base dir exists and the file exists (unless you're using FCREATE), it doesn't error.
