### ISSUE TITLE
Nightlies stopped

### ISSUE THREAD

**Issue by EvelynSubarrow** [Rinnegatamante/lpp-vita#57]
Hello!

It looks like the nightlies stopped being released somewhere around the start of 2020. I've tried to build a version of lpp-vita myself but I'm not absolutely sure of everything I'm doing and got tripped up by luajit. I'm not a C person, recent builds would be enormously helpful

**Comment by Rinnegatamante** [comment]
They're not: https://github.com/Rinnegatamante/lpp-vita/releases/tag/Nightly

**Comment by EvelynSubarrow** [comment]
The reason I asked this is because the latest tagged release has a date of 2020-01-16 on github, but also all of the files within the archives have the exact same date. If I use the latest commit for example, which affected `azure-pipelines.yml`, that has a listed date of ‎2020-01-15 within thte archive. The changelog is being progressively updated, but it looks like those files are not.

I've also tested eboot_unsafe.bin against a later feature and that does appear to be up to date however, which is what I was after in any event, so my apologies. Thank you for replying so quickly!

**Comment by Rinnegatamante** [comment]
The reported date for the artifact doesn't get updated by Azure Pipelines. You can however check the commits list in the nightly page and then check the date of those commits in the repo to know if the build is up to date.
