### ISSUE TITLE
Can't draw image...

### ISSUE THREAD

**Issue by valentinbreiz** [Rinnegatamante/lpp-vita#6]
Hello I'm on LPP Vita v4 and I can't draw iamges.
It's work with the "image sample" but no with my image. I use jpg, png nothing work.
It's give me that error : (C2-12828-1)
Saved Core File Succeeded
ux0:data/psp2core-1472001169-0x0000283fdb-eboot.bin.psp2dmp

And that's my code:

white = Color.new(255,255,255,255) 
fond = Graphics.loadImage("ux0:/app/CALC00001/medias/fond.png")
while true do
	Graphics.initBlend()
	Screen.clear()
	Graphics.debugPrint(850, 5, "version 0.1", white)
	Graphics.debugPrint(10, 5, "Calculatrice", white)
	Graphics.drawImage(50, 50, fond)
	Graphics.termBlend()
	Screen.flip()
	if Controls.check(Controls.read(), SCE_CTRL_START) then
		System.exit()
	end
end

**Comment by Rinnegatamante** [comment]
Can you use latest nightly and check if it solve the problem?
If not please upload your coredump file.

**Comment by valentinbreiz** [comment]
Sorry I don't understand? The latest nightly what?

**Comment by Rinnegatamante** [comment]
"Nightly Builds

We offer an automated builder service for our nightly builds. Nightly builds are automatically updated every 4 hours by a server we own. To take advantage of this service, you should visit this page."

From README...

**Comment by valentinbreiz** [comment]
Oh thank you very much! I will try :)

**Comment by valentinbreiz** [comment]
Wtf... With the new archive I got a black screen, even with the Hello World

**Comment by Rinnegatamante** [comment]
Try to replace eboot.bin in your lpp-builder/build folder with this: http://rinnegatamante.it/eboot.bin

**Comment by valentinbreiz** [comment]
It's work with my picture! :dancer:

**Comment by Rinnegatamante** [comment]
Nightly should work now anyway.
