### ISSUE TITLE
[Feature Request] System.extractSfo upgrade

### ISSUE THREAD

**Issue by BlackSheepBoy69** [Rinnegatamante/lpp-vita#64]
Hi, thank you for your excellent work on LPP!!! I'd like System.extractSfo to be upgraded.

~~1: When using System.extractSfo on several games (Flop Rocket, I Was Rebuilt, etc) the apptitle gets corrupted. This is best showcased in HexLauncher Custom v1.0.1 if you press triangle repeatedly while highlighting these games. It either cuts off the apptitle or adds corruption at the end or extremely rarely crashes the app.~~

2: I'd also like to be able to extract ID's and app titles from PSP .iso files, which seem to have a similar format to Vita .sfo files.

**Comment by jimbob4000** [comment]
Thanks for your help and support to date Rinne!

I'd love to see this happen, but appreciate it's a different sdk. 

Sfo reading from pbp, sfo and iso would be awesome. 

Onelua also has image extraction from these files, but it's quite slow.

**Comment by Rinnegatamante** [comment]
OneLua is closed source (and breaking GPL license over multiple instances). Just reformulate the Issue into what is being requested without referencing functions from it please since I don't know (and don't want to learn) its API.

**Comment by BlackSheepBoy69** [comment]
References to OneLua have been removed.

**Comment by Rinnegatamante** [comment]
I still see a wall of text with just cross references to "other lua version". Can't you just summarize in 2 lines what needs to be changed?

**Comment by BlackSheepBoy69** [comment]
Text de-walled.

**Comment by Rinnegatamante** [comment]
Can you provide a sample program to reproduce 1?

**Comment by BlackSheepBoy69** [comment]
Yes 1 sec

**Comment by BlackSheepBoy69** [comment]
https://github.com/MDashK/Flop-Rocket-Vita/releases/tag/v1.0.0

Shows up as "Flop Rocket" in "other" Lua programs. Shows up as either "Flop Rocke" or "Flop Rocke[many random symbols]" in Lua Player Plus

**Comment by Rinnegatamante** [comment]
i was refering to a drag'n'drop sample if possible. (A vpk with the faulty sfo and a minimalistic lua script reproducing the issue)

**Comment by Rinnegatamante** [comment]
Check if this solves 1 without adding any new bugs, please.
[eboot_safe.zip](https://github.com/Rinnegatamante/lpp-vita/files/9895698/eboot_safe.zip)

**Comment by Rinnegatamante** [comment]
Nightly also has System.extractPbp added and support for PARAM.SFO parsing inside PBP files via System.extractSfo.

As for ISO/CSO, any small (legal to share) sample app i can use?

**Comment by BlackSheepBoy69** [comment]
Sorry I thought you meant like a Vita program, I didn't think about sending you a Lua, sorry.
I'm now noticing on some Japanese games that they have a lot longer names now. Instead of "Dragon Quest Heroes II" (actual: ドラゴンクエストヒーローズⅡ) It now says "Dragon Quest Heroes II The Twin Kings and the End of Prophecy" (actual: ドラゴンクエストヒーローズⅡ　双子の王と予言の終わり) So I think this was not only an issue with homebrews. Flop Rocket is showing up good. Now that I go back and check this affected a lot of Japanese title games. Tildes - "~" - are now showing up in apptitles though they never did before. It makes me notice how ugly they are in the font I've been using lol.

Among Us (top file, the ZIP archive) contains an (I assume) legal CSO.
https://archive.org/download/among-us-psp-edition-alphanew.-7z

**Comment by BlackSheepBoy69** [comment]
Not sure if this is related, but an old eboot from a few months ago gives different results from this one for writing cache.

Specifically the code being:

        for key, val in pairs(v) do
            local sanitized_value
            ...
            file:write(tostring(sanitized_value) .. "\t")
            ...
        end

The order is all changed now compared to how it was a few months ago, is there any chance you could revert the "for pairs" order?

**Comment by Rinnegatamante** [comment]
> Not sure if this is related, but an old eboot from a few months ago gives different results from this one for writing cache.
> 
> Specifically the code being:
> 
> ```
>     for key, val in pairs(v) do
>         ...
>         file:write(tostring(sanitized_value) .. "\t")
>         ...
>     end
> ```
> 
> The order is all changed now compared to how it was a for the last few years (ex: in the a few months old eboot), is there any chance you could revert the "for pairs" order? The new order makes the cache look kind of ugly so I was hoping it could be reverted instead of me re-adapting the code and using the ugly cache As I said, not sure if this is related to the new param.sfo bugfix or not, this might just be nitpicking sorry.

Don't see how this is any related to the topic of this issue. (And i also didn't understand what you meant).

**Comment by Rinnegatamante** [comment]
As for the CSO/ISO, can you also provide an ISO?

**Comment by BlackSheepBoy69** [comment]
I converted the amogus to .iso because I couldn't find any legal iso files.

https://www.mediafire.com/file/hd03pyuqwze9xg8/amogus.iso/file

**Comment by Rinnegatamante** [comment]
> I converted the amogus to .iso because I couldn't find any legal iso files. (.cso is just the compressed version of .iso)
> 
> https://www.mediafire.com/file/hd03pyuqwze9xg8/amogus.iso/file

is this iso file even working? It has like 90 MB of null bytes at start.

**Comment by BlackSheepBoy69** [comment]
Sorry I'll test now.

**Comment by Rinnegatamante** [comment]
To be precise 103mb of null bytes.

**Comment by BlackSheepBoy69** [comment]
The amogus.iso does in fact work

**Comment by Rinnegatamante** [comment]
In order to extract anything from that ISO, i'd need to do a mem scan of 103 mb. Unless you want to extract your data taking 10 minutes per extraction, i guess stick to oneLua at this point 🤷 .
I'm also not a fan of adding features that are nowhere related to PSVita into the interpreter starting with and you could also implement those features on your own with io (same applies for SFO and PBP extraction btw).

**Comment by BlackSheepBoy69** [comment]
>you could also implement those features on your own with io directly in Lua

I don't understand what "io" means in this case, please explain?

**Comment by Rinnegatamante** [comment]
https://www.lua.org/pil/21.1.html

**Comment by BlackSheepBoy69** [comment]
I was trying to use io.read but I couldn't figure out how to use inp:seek("set", ...) to find where the ID and apptitle starts. I tried doing like the documentation says for PSP iso's but I couldn't get it to work. I believe I was using inp:seek("set", "0X10") and/or inp:seek("set", 0X10) but couldn't get it to read a PSP ID

**Comment by BlackSheepBoy69** [comment]
bump. editted above comment

**Comment by Rinnegatamante** [comment]
ISO files are not PBP files.

**Comment by BlackSheepBoy69** [comment]
I don't know, messing with this stuff makes me feel so dumb and I can never figure it out. I'm just gonna use OneLua...

**Comment by BlackSheepBoy69** [comment]
> Check if this solves 1 without adding any new bugs, please. [eboot_safe.zip](https://github.com/Rinnegatamante/lpp-vita/files/9895698/eboot_safe.zip)

There is 1 new bug where the app titles become exessively long sometimes, like "Atelier Ronona Plus" becomes "Atelier Ronona Plus ~The Alchemist of Arland~" and as I said a lot of Japanese games become really long named, maybe excessively long. It's cool to know that there was more details in these names but I was thinking it might be too much. I was just hoping for Flop Rocket to show up correctly which it does.

Maybe you would want to set the release as a full release with a name like "lpp-vita r7", then revert it? Or to make it a new command like System.extractSfoExtended? I'm not sure people would want the really long names sorry.

**Comment by Rinnegatamante** [comment]
That's not bug.
