### ISSUE TITLE
STITLE

### ISSUE THREAD

**Issue by BlackSheepBoy69** [Rinnegatamante/lpp-vita#67]
Hi again, sorry to keep bothering you with issues. When you fixed this issue (https://github.com/Rinnegatamante/lpp-vita/issues/64) it caused a different issue.

The new eboot does this:

	info = System.extractSfo("ux0:/app/PCSE00466/sce_sys/param.sfo")
	apptitle = info.title
	>>>>> apptitle is "Atelier Ronona Plus ~ The Alchemist of Arland" <<<<<

I guess the reason is inside the param.sfo is listed 2 titles: one listed as just "TITLE" and the other listed as "STITLE".

The old eboot used to take the title out of the STITLE field of param.sfo... so apptitle used to be just "Atelier Ronona Plus" which is how it shows up in the LiveArea. I'm was hoping you could upgrade System.extractSfo() to be able to output the STITLE so it can match how it looks on the LiveArea please. Maybe so it could be like this?:

	info = System.extractSfo("ux0:/app/PCSE00466/sce_sys/param.sfo")
	spptitle = info.stitle
	apptitle = info.title
	>>>>> spptitle is "Atelier Ronona Plus" <<<<<
	>>>>> apptitle is "Atelier Ronona Plus ~ The Alchemist of Arland" <<<<<

It might seem unnecessary but it would help a lot for RetroFlow and my project. The way it is right now makes the app titles so long they go offscreen and don't match the app titles in the LiveArea. That's why we're hoping you can make it have info.stitle so we don't have to keep using the ancient Lua Player Plus eboots. Since the URI issue has been solved in the latest eboot ( https://github.com/Rinnegatamante/lpp-vita/issues/66 ) me and jimbob4000 were wanting to use the latest Lua Player Plus but couldn't because of this issue

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/lpp-vita/commit/4ca3b2d9b6b5fe1abcc7e1571b542dd37cbfd322

**Comment by BlackSheepBoy69** [comment]
Daaaaang that was fast. Thanks again you're the best!
