### ISSUE TITLE
SCE_CTRL_CONFIRM

### ISSUE THREAD

**Issue by BlackSheepBoy69** [Rinnegatamante/lpp-vita#69]
Hi, once again thank you for your good work on Lua Player Plus.

I had an issue with Controls.getEnterButton() and drawing the correct image for X/O. This might make HexFlow Custom/RetroFlow a little easier to use and save a space in the apps's start menus since Controls.getEnterButton() is very fast and it wouldn't require making a setting for checking whether to swap X/O anymore.

How it is now:

	pad = Controls.read()
	SCE_CTRL_CONFIRM = Controls.getEnterButton()
	Graphics.drawImage(824, 510, btnX) --Might draw the wrong image
	if Controls.check(pad, SCE_CTRL_CONFIRM) then
	    accepted = yes
	end

Maybe it could be like this, so that the right "enter button" image can be drawn?

	pad = Controls.read()
	SwapXO = Controls.getEnterButton()
	if SwapXO == 1 then
	    Graphics.drawImage(824, 510, btnX)
	    Font.print(fnt20, 852, 508, "Accept", white)
	    if Controls.check(pad, SCE_CTRL_CROSS) then
	        accepted = true
	    end
	elseif SwapXO == 0 then
	    Graphics.drawImage(824, 510, btnO)
	    Font.print(fnt20, 852, 508, "Accept", white)
	    if Controls.check(pad, SCE_CTRL_CIRCLE) then
	        accepted = true
	    end
	end

Thank you in advance if you add this feature. I feel it would be a good addition and it wouldn't be too much of a code hog.

**Comment by Rinnegatamante** [comment]
if SCE_CTRL_CONFIRM == SCE_CTRL_CROSS then
SCE_CTRL_CANCEL = SCE_CTRL_CIRCLE
else
SCE_CTRL_CANCEL = SCE_CTRL_CROSS
end

**Comment by BlackSheepBoy69** [comment]
Thanks 👍
