### ISSUE TITLE
Undeletable Apps

### ISSUE THREAD

**Issue by ItsDeidara** [Rinnegatamante/lpp-vita#8]
About 50% of the apps that I generate from my lua code can't be deleted from the psvita. Not even rebuilding the database will solve this issue.

**Comment by Rinnegatamante** [comment]
That's cause you've not followed the instructions in lpp-builder. Title ID must contain only UPPERCASEs.

**Comment by gnmmarechal** [comment]
Shameless self plug ftw

http://gbatemp.net/index.php?threads/438753/
